version: '3'
services:
  backend:
    build: ./backend
    expose: 
      - 3001
    ports: 
      - 3001:3001
    command: npm start 
  frontend:
    build: ./frontend
    expose: 
      - 3000
    ports: 
      - 3000:3000
    command: npm start 
